"""
render_card.py

Renders a PAGASA NCR-PRSD advisory as a clean PNG "info card" image:
a colored header (color depends on advisory type), the heading, issued
time, and the full advisory body text, word-wrapped.

This is NOT a geographic map -- see README.md for why (the real PAGASA
map graphic is generated by a live JS map on panahon.gov.ph that we can't
reliably reproduce, and free Philippine boundary data we could source is
missing some provinces PAGASA regularly mentions, e.g. Tarlac).
"""

import textwrap
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ASSETS_DIR = Path(__file__).parent / "assets"
FONT_REGULAR = ASSETS_DIR / "fonts" / "DejaVuSans.ttf"
FONT_BOLD = ASSETS_DIR / "fonts" / "DejaVuSans-Bold.ttf"

CARD_WIDTH = 900
PADDING = 40
HEADER_HEIGHT = 130

# RGB colors per advisory type (matches the Discord embed colors)
CARD_COLORS = {
    "thunderstorm watch": (241, 196, 15),        # yellow
    "thunderstorm advisory": (230, 126, 34),      # orange
    "thunderstorm information": (149, 165, 166),  # grey
    "rainfall advisory": (52, 152, 219),          # blue
    "heavy rainfall warning": (231, 76, 60),      # red
}
DEFAULT_COLOR = (46, 204, 113)  # green fallback


def _font(path: Path, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(path), size)


def _wrap_text(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont, max_width: int) -> list[str]:
    """Word-wrap text to fit max_width, respecting existing newlines."""
    lines = []
    for paragraph in text.split("\n"):
        if not paragraph.strip():
            lines.append("")
            continue
        words = paragraph.split(" ")
        current = ""
        for word in words:
            trial = f"{current} {word}".strip()
            if draw.textlength(trial, font=font) <= max_width:
                current = trial
            else:
                if current:
                    lines.append(current)
                current = word
        if current:
            lines.append(current)
    return lines


def render_advisory_card(advisory: dict) -> bytes:
    """
    Render one advisory dict (as produced by watch_pagasa.extract_advisories)
    into a PNG image. Returns raw PNG bytes.
    """
    color = CARD_COLORS.get(advisory["type"], DEFAULT_COLOR)

    font_eyebrow = _font(FONT_REGULAR, 20)
    font_heading = _font(FONT_BOLD, 32)
    font_issued = _font(FONT_REGULAR, 20)
    font_body = _font(FONT_REGULAR, 22)

    # Use a throwaway image just to measure text before we know final height
    measurer = ImageDraw.Draw(Image.new("RGB", (10, 10)))
    body_lines = _wrap_text(measurer, advisory["body"], font_body, CARD_WIDTH - 2 * PADDING)
    heading_lines = _wrap_text(measurer, advisory["heading"], font_heading, CARD_WIDTH - 2 * PADDING)

    line_height = 30
    body_block_height = max(len(body_lines), 1) * line_height
    heading_block_height = max(len(heading_lines), 1) * 40

    total_height = (
        HEADER_HEIGHT
        + heading_block_height
        + 50  # issued-at line + spacing
        + 20  # divider spacing
        + body_block_height
        + PADDING * 2
        + 40  # footer
    )
    total_height = max(total_height, 400)

    img = Image.new("RGB", (CARD_WIDTH, int(total_height)), "white")
    draw = ImageDraw.Draw(img)

    # Header band
    draw.rectangle([0, 0, CARD_WIDTH, HEADER_HEIGHT], fill=color)
    draw.text((PADDING, 20), "DOST-PAGASA", font=font_eyebrow, fill="white")
    draw.text((PADDING, 45), "National Capital Region \u2013 PAGASA Regional Services Division", font=font_eyebrow, fill="white")
    draw.text((PADDING, 80), "Regional Weather Forecasting Center", font=font_eyebrow, fill="white")

    y = HEADER_HEIGHT + 30

    # Heading
    for line in heading_lines:
        draw.text((PADDING, y), line, font=font_heading, fill=(30, 30, 30))
        y += 40

    y += 5
    draw.text((PADDING, y), f"Issued at: {advisory['issued_at'].replace('Issued at:', '').strip()}", font=font_issued, fill=(90, 90, 90))
    y += 40

    # Divider
    draw.line([(PADDING, y), (CARD_WIDTH - PADDING, y)], fill=(220, 220, 220), width=2)
    y += 25

    # Body
    for line in body_lines:
        draw.text((PADDING, y), line, font=font_body, fill=(40, 40, 40))
        y += line_height

    # Footer
    footer_y = int(total_height) - 35
    draw.line([(PADDING, footer_y - 10), (CARD_WIDTH - PADDING, footer_y - 10)], fill=(230, 230, 230), width=1)
    draw.text(
        (PADDING, footer_y),
        "Source: pagasa.dost.gov.ph/regional-forecast/ncrprsd",
        font=_font(FONT_REGULAR, 16),
        fill=(150, 150, 150),
    )

    from io import BytesIO
    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()
