"""
render_card.py

Renders a PAGASA NCR-PRSD advisory as a PNG image with two parts:
  1. An info card -- colored header, heading, issued time, full body text.
  2. A schematic area map -- a simple tile grid of NCR + the ~12 surrounding
     provinces PAGASA's NCR-PRSD regularly names, color-coded by whether each
     is EXPECTING conditions, currently AFFECTING, or not mentioned.

Why "schematic" and not a real geographic map: PAGASA's own map graphic is
generated by a live JS map on panahon.gov.ph, which isn't something a script
can fetch as a static file. Free Philippine boundary data that could be used
to draw a real geographic map turned out to be missing some provinces PAGASA
mentions constantly (Tarlac, notably) -- so instead of a real map with holes
in it, this draws a deliberately simplified tile-grid layout (correct
relative position/adjacency, not to scale or accurate coastlines) that's
guaranteed to include every area PAGASA might mention. It's accurate about
*which areas are affected*, which is the part that actually matters for an
alert -- just not a survey-accurate map.
"""

import re
import textwrap
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ASSETS_DIR = Path(__file__).parent / "assets"
FONT_REGULAR = ASSETS_DIR / "fonts" / "DejaVuSans.ttf"
FONT_BOLD = ASSETS_DIR / "fonts" / "DejaVuSans-Bold.ttf"

CARD_WIDTH = 900
PADDING = 40
HEADER_HEIGHT = 130

# RGB colors per advisory type (matches the Discord embed colors)
CARD_COLORS = {
    "thunderstorm watch": (241, 196, 15),        # yellow
    "thunderstorm advisory": (230, 126, 34),      # orange
    "thunderstorm information": (149, 165, 166),  # grey
    "rainfall advisory": (52, 152, 219),          # blue
    "heavy rainfall warning": (231, 76, 60),      # red
}
DEFAULT_COLOR = (46, 204, 113)  # green fallback

# --- Schematic area map ------------------------------------------------

# Row/column position for each tile. Deliberately a simplified grid, not
# real coordinates -- but the relative arrangement (what's north/south/east/
# west of what) matches actual geography so it still reads intuitively.
MAP_GRID = {
    "Zambales":     (0, 0),
    "Tarlac":       (0, 1),
    "Nueva Ecija":  (0, 2),
    "Aurora":       (0, 3),
    "Bataan":       (1, 0),
    "Pampanga":     (1, 1),
    "Bulacan":      (1, 2),
    "Cavite":       (2, 0),
    "Metro Manila": (2, 1),
    "Rizal":        (2, 2),
    "Batangas":     (3, 0),
    "Laguna":       (3, 1),
    "Quezon":       (3, 2),
}
MAP_COLS = 4
MAP_ROWS = 4

TILE_W = 190
TILE_H = 80
TILE_GAP = 10

COLOR_UNAFFECTED = (222, 226, 230)
COLOR_EXPECTING = (242, 108, 169)   # pink, matches PAGASA's "expecting" shade
COLOR_AFFECTING = (75, 24, 120)     # purple, matches PAGASA's "affecting" shade
COLOR_AFFECTED_GENERIC = (230, 126, 34)  # orange, used when we can't tell expecting vs. affecting apart

# NCR cities that should light up the single "Metro Manila" tile
_NCR_CITIES = [
    "Caloocan", "Las Piñas", "Las Pinas", "Makati", "Malabon", "Mandaluyong",
    "Manila", "Marikina", "Muntinlupa", "Navotas", "Parañaque", "Paranaque",
    "Pasay", "Pasig", "Pateros", "Quezon City", "San Juan", "Taguig", "Valenzuela",
]
_NCR_GENERIC = ["Metro Manila", "Greater Metro Manila Area", "National Capital Region", "NCR"]


def _area_pattern(name: str) -> str:
    if name == "Quezon":
        # Avoid matching the "Quezon" inside "Quezon City" (that's NCR, not
        # Quezon province)
        return r"\bQuezon\b(?!\s+City)"
    if name == "Manila":
        return r"(?<!Metro )(?<!Greater Metro )\bManila\b"
    return r"\b" + re.escape(name) + r"\b"


def _text_mentions_area(text: str, area: str) -> bool:
    if area == "Metro Manila":
        return any(
            re.search(_area_pattern(c), text, flags=re.IGNORECASE) for c in _NCR_CITIES
        ) or any(
            re.search(r"\b" + re.escape(g) + r"\b", text, flags=re.IGNORECASE) for g in _NCR_GENERIC
        )
    return bool(re.search(_area_pattern(area), text, flags=re.IGNORECASE))


def compute_area_status(body: str) -> dict[str, str]:
    """
    Return {area_name: status} for every MAP_GRID area mentioned in body,
    where status is 'expecting', 'affecting', or 'affected' (generic, used
    when the advisory doesn't split into EXPECTING/AFFECTING sections).
    """
    status: dict[str, str] = {}

    m_exp = re.search(r"EXPECTING\s*:(.*?)(?=\bAFFECTING\s*:|\Z)", body, re.IGNORECASE | re.DOTALL)
    m_aff = re.search(r"AFFECTING\s*:(.*?)\Z", body, re.IGNORECASE | re.DOTALL)

    if m_exp or m_aff:
        if m_exp:
            for area in MAP_GRID:
                if _text_mentions_area(m_exp.group(1), area):
                    status[area] = "expecting"
        if m_aff:
            for area in MAP_GRID:
                if _text_mentions_area(m_aff.group(1), area):
                    status[area] = "affecting"  # overrides 'expecting' if both
    else:
        for area in MAP_GRID:
            if _text_mentions_area(body, area):
                status[area] = "affected"

    return status


def _draw_area_map(draw: ImageDraw.ImageDraw, top_left: tuple[int, int], area_status: dict[str, str]) -> int:
    """Draw the schematic tile grid starting at top_left. Returns its height."""
    x0, y0 = top_left
    font_tile = _font(FONT_BOLD, 15)
    font_caption = _font(FONT_REGULAR, 15)
    font_legend = _font(FONT_REGULAR, 15)

    for area, (row, col) in MAP_GRID.items():
        status = area_status.get(area)
        color = {
            "expecting": COLOR_EXPECTING,
            "affecting": COLOR_AFFECTING,
            "affected": COLOR_AFFECTED_GENERIC,
        }.get(status, COLOR_UNAFFECTED)
        text_color = "white" if status else (80, 80, 80)

        tx = x0 + col * (TILE_W + TILE_GAP)
        ty = y0 + row * (TILE_H + TILE_GAP)
        draw.rounded_rectangle([tx, ty, tx + TILE_W, ty + TILE_H], radius=10, fill=color)

        # Word-wrap the (short) area name inside the tile
        words = area.split(" ")
        lines, current = [], ""
        for w in words:
            trial = f"{current} {w}".strip()
            if draw.textlength(trial, font=font_tile) <= TILE_W - 16:
                current = trial
            else:
                lines.append(current)
                current = w
        if current:
            lines.append(current)

        text_h = len(lines) * 20
        ly = ty + (TILE_H - text_h) // 2
        for line in lines:
            lw = draw.textlength(line, font=font_tile)
            draw.text((tx + (TILE_W - lw) / 2, ly), line, font=font_tile, fill=text_color)
            ly += 20

    map_height = MAP_ROWS * TILE_H + (MAP_ROWS - 1) * TILE_GAP

    # Legend, to the right of the grid if there's room, else below
    legend_x = x0 + MAP_COLS * (TILE_W + TILE_GAP)
    legend_items = [
        (COLOR_EXPECTING, "Expecting"),
        (COLOR_AFFECTING, "Currently affecting"),
        (COLOR_AFFECTED_GENERIC, "Affected (see text)"),
        (COLOR_UNAFFECTED, "Not mentioned"),
    ]
    ly = y0
    for color, label in legend_items:
        draw.rounded_rectangle([legend_x, ly, legend_x + 22, ly + 22], radius=4, fill=color)
        draw.text((legend_x + 32, ly + 3), label, font=font_legend, fill=(60, 60, 60))
        ly += 34

    caption_y = y0 + map_height + 12
    draw.text(
        (x0, caption_y),
        "Schematic layout (relative position only, not to scale/accurate coastlines)",
        font=font_caption,
        fill=(150, 150, 150),
    )

    return map_height + 12 + 20  # grid + caption spacing


def _font(path: Path, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(path), size)


def _wrap_text(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont, max_width: int) -> list[str]:
    """Word-wrap text to fit max_width, respecting existing newlines."""
    lines = []
    for paragraph in text.split("\n"):
        if not paragraph.strip():
            lines.append("")
            continue
        words = paragraph.split(" ")
        current = ""
        for word in words:
            trial = f"{current} {word}".strip()
            if draw.textlength(trial, font=font) <= max_width:
                current = trial
            else:
                if current:
                    lines.append(current)
                current = word
        if current:
            lines.append(current)
    return lines


def render_advisory_card(advisory: dict) -> bytes:
    """
    Render one advisory dict (as produced by watch_pagasa.extract_advisories)
    into a PNG image (info card + schematic area map). Returns raw PNG bytes.
    """
    color = CARD_COLORS.get(advisory["type"], DEFAULT_COLOR)

    font_eyebrow = _font(FONT_REGULAR, 20)
    font_heading = _font(FONT_BOLD, 32)
    font_issued = _font(FONT_REGULAR, 20)
    font_body = _font(FONT_REGULAR, 22)
    font_section = _font(FONT_BOLD, 20)

    area_status = compute_area_status(advisory["body"])
    map_width = MAP_COLS * (TILE_W + TILE_GAP) + 180  # + legend column
    canvas_width = max(CARD_WIDTH, map_width + 2 * PADDING)

    # Use a throwaway image just to measure text before we know final height
    measurer = ImageDraw.Draw(Image.new("RGB", (10, 10)))
    body_lines = _wrap_text(measurer, advisory["body"], font_body, canvas_width - 2 * PADDING)
    heading_lines = _wrap_text(measurer, advisory["heading"], font_heading, canvas_width - 2 * PADDING)

    line_height = 30
    body_block_height = max(len(body_lines), 1) * line_height
    heading_block_height = max(len(heading_lines), 1) * 40
    map_block_height = MAP_ROWS * TILE_H + (MAP_ROWS - 1) * TILE_GAP + 12 + 20 if area_status or True else 0

    total_height = (
        HEADER_HEIGHT
        + heading_block_height
        + 50  # issued-at line + spacing
        + 20  # divider spacing
        + body_block_height
        + 30  # spacing before map section
        + 35  # "Affected areas" section title
        + map_block_height
        + PADDING * 2
        + 40  # footer
    )
    total_height = max(total_height, 400)

    img = Image.new("RGB", (canvas_width, int(total_height)), "white")
    draw = ImageDraw.Draw(img)

    # Header band
    draw.rectangle([0, 0, canvas_width, HEADER_HEIGHT], fill=color)
    draw.text((PADDING, 20), "DOST-PAGASA", font=font_eyebrow, fill="white")
    draw.text((PADDING, 45), "National Capital Region \u2013 PAGASA Regional Services Division", font=font_eyebrow, fill="white")
    draw.text((PADDING, 80), "Regional Weather Forecasting Center", font=font_eyebrow, fill="white")

    y = HEADER_HEIGHT + 30

    # Heading
    for line in heading_lines:
        draw.text((PADDING, y), line, font=font_heading, fill=(30, 30, 30))
        y += 40

    y += 5
    draw.text((PADDING, y), f"Issued at: {advisory['issued_at'].replace('Issued at:', '').strip()}", font=font_issued, fill=(90, 90, 90))
    y += 40

    # Divider
    draw.line([(PADDING, y), (canvas_width - PADDING, y)], fill=(220, 220, 220), width=2)
    y += 25

    # Body (the "WORDS")
    for line in body_lines:
        draw.text((PADDING, y), line, font=font_body, fill=(40, 40, 40))
        y += line_height

    y += 30

    # Schematic area map (the "MAP")
    draw.text((PADDING, y), "Affected areas (schematic map)", font=font_section, fill=(30, 30, 30))
    y += 35
    _draw_area_map(draw, (PADDING, y), area_status)
    y += map_block_height

    # Footer
    footer_y = int(total_height) - 35
    draw.line([(PADDING, footer_y - 10), (canvas_width - PADDING, footer_y - 10)], fill=(230, 230, 230), width=1)
    draw.text(
        (PADDING, footer_y),
        "Source: pagasa.dost.gov.ph/regional-forecast/ncrprsd",
        font=_font(FONT_REGULAR, 16),
        fill=(150, 150, 150),
    )

    from io import BytesIO
    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()
